### Recuperar todos los usuarios
GET http://localhost:3000/users

### Registrar un usuario
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "pablo004",
  "password": "abc123"
}

### Iniciar sesión
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "pablo004",
  "password": "abc123"
}

### Refresh token
POST http://localhost:3000/users/refresh-token
x-refresh-token: bd041c74dcb9e7b4ce41c39af45861e39a8c769379ab71ccab290940082516dcb78613d7c19bed8b413b073e427b2ca691ef05a426edd99d4c747c6fdde2aacb

### Recuperar la información de uno mismo
POST http://localhost:3000/users/get-self-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMDA0IiwiaWF0IjoxNzY3MzEwMzk3LCJleHAiOjE3NjczMTA0NTd9.lvhi9pM9_NEm4J9kIIbdnU9Hjwluo1NJMnKvhb86yVI