### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar una película por ID
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Filtrar películas por género
GET http://localhost:3000/movies?genre=action

### Crear una película
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://m.media-amazon.com/images/I/51rOnIjLqzL._AC_.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una película
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 1998
}

### Recuperar todos los usuarios
GET http://localhost:3000/users

### Registrar un usuario
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "pablo004",
  "password": "abc123"
}

### Iniciar sesión
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "pablo004",
  "password": "abc123"
}

### Refresh token
POST http://localhost:3000/users/refresh-token
Content-Type: application/json

{
  "refresh_token": "3e89f504b162fdad4f90deb43356f40c22ca752147749c4982cc0302ff91851eb9bd494b04cb070818e50d5991425d3409c586c8cfab21cbb9eab145c1c59c3c"
}

### Recuperar la información de uno mismo
POST http://localhost:3000/users/get-self-info
Content-Type: application/json

{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMDA0IiwiaWF0IjoxNzY3MTk5MTk0LCJleHAiOjE3NjcxOTkyNTR9.7Md2mNADkG4ABpyERXQn9qI4bPcwcVqnvDebFljjPjQ"
}