### Recuperar todos los usuarios
GET http://localhost:3000/users

### Registrar un usuario
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "pablo010",
  "password": "abc123"
}

### Iniciar sesión
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "pablo004",
  "password": "abc123"
}

### Refresh token
POST http://localhost:3000/users/refresh-token
x-refresh-token: bd041c74dcb9e7b4ce41c39af45861e39a8c769379ab71ccab290940082516dcb78613d7c19bed8b413b073e427b2ca691ef05a426edd99d4c747c6fdde2aacb

### Recuperar la información de uno mismo
POST http://localhost:3000/users/get-self-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMDA0IiwiaWF0IjoxNzY3NTUzMDA2LCJleHAiOjE3Njc1NTM5MDZ9.D-jwUI__i_bBtaJIrhIRs6j9ZJjI4qWXEn3Z-f-39jI

### Cambiar nombre real
PATCH http://localhost:3000/users/update-real-name
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMDA0IiwiaWF0IjoxNzY3MzE4OTAzLCJleHAiOjE3NjczMTk4MDN9.IbTcuaMyFMF2e48U0Z1koDtfl_Q0INqlUY0CGRFAqEo
Content-Type: application/json

{
  "real_name": "Pablo Updated"
}

### Comprobar si el username enviado existe en la BD
POST http://localhost:3000/users/check-username-availability
Content-Type: application/json

{
  "username": "pablo004"
}